blueprint:
  name: A1 - Sunrise and Sunset Automation
  description: |
    # 🔆 Sunrise and Sunset Lighting Automation 🔆

    This blueprint automates your home lighting based on the sun's position,
    ensuring that your lighting aligns perfectly with the natural daylight cycle.

    **Flip Light Action:**
    - If TRUE, the light action is flipped: turning ON at sunrise and OFF at sunset.
    - If FALSE, the light will turn OFF at sunrise and ON at sunset.

  domain: automation
  input:
    trigger_at_startup:
      name: Trigger at Startup
      description: Trigger actions at startup if conditions are met.
      default: true
      selector:
        boolean:

    flip_light_action:
      name: Flip Light Action
      description: |
        If TRUE, the light action is flipped:
        - Turning ON at sunrise and turning OFF at sunset.
        If FALSE, the light will turn OFF at sunrise and turn ON at sunset.
      default: false
      selector:
        boolean:

    sunrise_elevation_shift:
      name: Sunrise Elevation Shift
      description: Threshold for sunrise actions (-6° to 6°).
      default: -1.5
      selector:
        number:
          min: -6
          max: 6
          unit_of_measurement: "°"

    sunset_elevation_shift:
      name: Sunset Elevation Shift
      description: Threshold for sunset actions (-6° to 6°).
      default: -2
      selector:
        number:
          min: -6
          max: 6
          unit_of_measurement: "°"

    target_light:
      name: Target Light
      description: The light to control at sunrise and sunset.
      selector:
        entity:
          domain: light
      default: null

trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: !input sunset_elevation_shift
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: !input sunrise_elevation_shift
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: !input target_light
    from: 'unavailable'
    to: 'on'
  - platform: state
    entity_id: !input target_light
    from: 'unknown'
    to: 'on'
  - platform: state
    entity_id: !input target_light
    from: 'unknown'
    to: 'on'

condition:
  - condition: template
    value_template: "{{ target_light is not none }}"

  - condition: or
    conditions:
      # Sunset condition
      - condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'false'
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sunset_elevation_shift

      # Sunrise condition
      - condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'true'
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            above: !input sunrise_elevation_shift

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'false'
        sequence:
          - service: >
              {% if flip_light_action %}
                light.turn_on
              {% else %}
                light.turn_off
              {% endif %}
            target:
              entity_id: "{{ target_light }}"
      - conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'true'
        sequence:
          - service: >
              {% if flip_light_action %}
                light.turn_off
              {% else %}
                light.turn_on
              {% endif %}
            target:
              entity_id: "{{ target_light }}"
    default: []

mode: single
