blueprint:
  name: Actions at Sunrise and Sunset Elevation
  description: |
    Manage your lighting based on the sun's position.
    Set different elevation thresholds for turning lights on at sunrise
    and off at sunset to match your preferences and enhance automation.

  domain: automation
  input:
    # General Settings
    trigger_at_startup:
      name: Trigger at Startup
      description: Whether to trigger actions at startup if elevation conditions are met.
      default: true
      selector:
        boolean:

    # Sunset Settings
    sunset_elevation_shift:
      name: Sunset Elevation Shift
      description: Elevation shift value to compare against for sunset (-6° to 6°).
      default: -1.5
      selector:
        number:
          min: -6
          max: 6
          unit_of_measurement: "°"

    # Sunrise Settings
    sunrise_elevation_shift:
      name: Sunrise Elevation Shift
      description: Elevation shift value to compare against for sunrise (-6° to 6°).
      default: -2
      selector:
        number:
          min: -6
          max: 6
          unit_of_measurement: "°"

    # Light Settings
    target_light:
      name: Target Light
      description: The light to control at sunrise and sunset.
      selector:
        entity:
          domain: light

variables:
  trigger_at_startup: !input trigger_at_startup
  sunrise_elevation_shift: !input sunrise_elevation_shift
  sunset_elevation_shift: !input sunset_elevation_shift
  target_light: !input target_light

trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 0
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0
  - platform: homeassistant
    event: start

condition:
  - condition: or
    conditions:
      # Sunrise condition
      - condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'true'
          - condition: template
            value_template: >-
              {{ trigger.platform != "homeassistant" or 
                 (trigger_at_startup and state_attr("sun.sun", "elevation") >= sunrise_elevation_shift) }}
      # Sunset condition
      - condition: and
        conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'false'
          - condition: template
            value_template: >-
              {{ trigger.platform != "homeassistant" or 
                 (trigger_at_startup and state_attr("sun.sun", "elevation") <= sunset_elevation_shift) }}

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'true'
        sequence:
          # Action for sunrise: Turn on the light
          - service: light.turn_on
            target:
              entity_id: "{{ target_light }}"
      - conditions:
          - condition: state
            entity_id: sun.sun
            attribute: rising
            state: 'false'
        sequence:
          # Action for sunset: Turn off the light
          - service: light.turn_off
            target:
              entity_id: "{{ target_light }}"
    default: []

mode: single
